In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
!rm -f "/content/SWYNEX-Online-Retail-Analytics.xlsx"

In [ ]:
!wget -O "/content/OnlineRetail.zip" "https://archive.ics.uci.edu/static/public/352/online+retail.zip"

--2026-09-24 06:40:51--  https://archive.ics.uci.edu/static/public/352/online+retail.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘/content/OnlineRetail.zip’

/content/OnlineReta     [     <=>            ]  22.62M  24.3MB/s    in 0.9s

2026-09-24 06:40:53 (24.3 MB/s) - ‘/content/OnlineRetail.zip’ saved [23715478]

In [ ]:
!unzip -o "/content/OnlineRetail.zip" -d "/content/OnlineRetail"

Archive:  /content/OnlineRetail.zip
 extracting: /content/OnlineRetail/Online Retail.xlsx

In [ ]:
!unzip -o "/content/OnlineRetail.zip" -d "/content/OnlineRetail"

Archive:  /content/OnlineRetail.zip
 extracting: /content/OnlineRetail/Online Retail.xlsx

In [15]:
df=pd.read_excel("/content/SWYNEX-Online-Retail-Analytics.xlsx")

In [17]:
  df.shape

(541909, 8)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [25]:
df.duplicated().sum()

np.int64(5268)

In [26]:
  df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [45]:
df.columns=(df.columns.str.strip().str.replace(" ","_").str.lower())

In [44]:
df["Country"]

0         United Kingdom
1         United Kingdom
2         United Kingdom
3         United Kingdom
4         United Kingdom
               ...
541904            France
541905            France
541906            France
541907            France
541908            France
Name: Country, Length: 541909, dtype: object

In [47]:
df["country"].value_counts()

country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [50]:
df["country"] = df["country"].str.lower()

In [51]:
df["country"]

0         united kingdom
1         united kingdom
2         united kingdom
3         united kingdom
4         united kingdom
               ...
541904            france
541905            france
541906            france
541907            france
541908            france
Name: country, Length: 541909, dtype: object

In [53]:
df["country"].value_counts().head(20)

country
united kingdom     495478
germany              9495
france               8557
eire                 8196
spain                2533
netherlands          2371
belgium              2069
switzerland          2002
portugal             1519
australia            1259
norway               1086
italy                 803
channel islands       758
finland               695
cyprus                622
sweden                462
unspecified           446
austria               401
denmark               389
japan                 358
Name: count, dtype: int64

In [ ]:
#In simple words:

#"Show me which columns have missing data, how many are missing, and what percentage they represent."

In [54]:
missing = df.isnull().sum()

In [55]:
missing_percentage=(df.isnull().sum()/ len(df)) * 100

In [57]:
  df.isnull().sum()

invoiceno           0
stockcode           0
description      1454
quantity            0
invoicedate         0
unitprice           0
customerid     135080
country             0
dtype: int64

In [56]:
missing_percentage

invoiceno       0.000000
stockcode       0.000000
description     0.268311
quantity        0.000000
invoicedate     0.000000
unitprice       0.000000
customerid     24.926694
country         0.000000
dtype: float64

In [61]:
(df["quantity"] <= 0).sum()

np.int64(10624)

In [64]:
#counts products with 0 or negative price.
 (df["unitprice"] <=0).sum()

np.int64(2517)

In [70]:
cancelled = df["invoiceno"].astype(str).str.startswith("c")

In [73]:
cancelled.sum()

np.int64(0)

In [90]:
cancelled = df["invoiceno"].astype(str).str.startswith("c")

df_clean = df[~cancelled].copy()

In [91]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 5268

In [93]:
df_clean=df_clean.drop_duplicates()

In [94]:
print("missing descriptions:",df_clean["description"].isna().sum())

missing descriptions: 1454

In [97]:
df_clean=df_clean.dropna(subset=["description"])
df_clean

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,united kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,united kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,france
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,france
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,france
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,france
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,france

In [100]:
print("Final rows:", len(df_clean))
print("Final columns:", len(df_clean.columns))
print("Duplicates:", df_clean.duplicated().sum())
print("\nMissing values:")
print(df_clean.isnull().sum())

Final rows: 535187
Final columns: 8
Duplicates: 0

Missing values:
invoiceno           0
stockcode           0
description         0
quantity            0
invoicedate         0
unitprice           0
customerid     133583
country             0
dtype: int64